[package]
name = "datapuller_clean"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
eframe = "0.31.1"
rodio = "0.20.1"

[build-dependencies]
winres = "0.1"

[package.metadata.windows]
subsystem = "windows"